name: Deploy Lambda Function

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository to the GitHub runner
      - name: Checkout repository
        uses: actions/checkout@master

      # Step 2: Zip the 'notebook.py' file
      - name: Zip notebook.py
        run: zip lambda_function.zip insurancedb/notebook.py

      # Step 3: Deploy the Lambda function
      - name: Deploy Lambda Function
        run: |
          aws lambda create-function --function-name my_notebook_lambda \
            --runtime python3.8 --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_LAMBDA_ROLE }} \
            --handler notebook.lambda_handler --zip-file fileb://lambda_function.zip \
            --region us-west-1 || \
          aws lambda update-function-code --function-name my_notebook_lambda --zip-file fileb://lambda_function.zip --region us-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'
